/**
 * Phase 10.92 Day 1 (Enterprise Cleanup): Get Paper DTOs
 *
 * Enterprise-grade data transfer objects for GET /library/:paperId endpoint.
 * Provides type safety, validation, and comprehensive API documentation.
 *
 * **Enterprise Standards Applied**:
 * - ✅ Strong TypeScript typing (no 'any')
 * - ✅ Input validation with class-validator
 * - ✅ Comprehensive Swagger documentation
 * - ✅ CUID format validation
 * - ✅ Type-safe response structure
 */

import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, Matches } from 'class-validator';

/**
 * Request parameters DTO for GET /library/:paperId
 *
 * Validates paper ID format before database query.
 * Rejects invalid CUIDs with 400 Bad Request.
 */
export class GetPaperParamsDto {
  @ApiProperty({
    description: 'Paper ID in CUID format (generated by Prisma)',
    example: 'cmi2n24cl00079kt7xu9k82xo',
    type: String,
    pattern: '^c[a-z0-9]{24,}$',
  })
  @IsString({ message: 'Paper ID must be a string' })
  @IsNotEmpty({ message: 'Paper ID is required' })
  @Matches(/^c[a-z0-9]{24,}$/, {
    message: 'Paper ID must be a valid CUID format (starts with "c" followed by 24+ alphanumeric characters)',
  })
  paperId!: string;
}

/**
 * Paper details returned by GET /library/:paperId
 *
 * BUG FIX (Nov 19, 2025): Now includes full-text content and abstract
 * Previous issue: Frontend could not extract themes because content was missing
 *
 * Returns paper fields needed for theme extraction and analysis.
 */
export class PaperDetailsDto {
  @ApiProperty({
    description: 'Paper unique identifier (CUID)',
    example: 'cmi2n24cl00079kt7xu9k82xo',
  })
  id!: string;

  @ApiProperty({
    description: 'Paper title',
    example: 'A Comprehensive Review of Machine Learning in Healthcare',
  })
  title!: string;

  @ApiProperty({
    description: 'Digital Object Identifier (DOI)',
    example: '10.1234/example.2024',
    nullable: true,
  })
  doi!: string | null;

  @ApiProperty({
    description: 'PubMed ID',
    example: '12345678',
    nullable: true,
  })
  pmid!: string | null;

  @ApiProperty({
    description: 'Paper URL',
    example: 'https://example.com/paper.pdf',
    nullable: true,
  })
  url!: string | null;

  @ApiProperty({
    description: 'Full-text extraction status',
    enum: ['not_fetched', 'fetching', 'success', 'failed'],
    example: 'fetching',
    nullable: true,
  })
  fullTextStatus!: 'not_fetched' | 'fetching' | 'success' | 'failed' | null;

  @ApiProperty({
    description: 'Whether full-text content is available',
    example: false,
  })
  hasFullText!: boolean;

  @ApiProperty({
    description: 'Word count of full-text content',
    example: 5432,
    nullable: true,
  })
  fullTextWordCount!: number | null;

  @ApiProperty({
    description: 'Full-text content (if available) - BUG FIX (Nov 19, 2025)',
    example: 'Introduction\n\nThis paper explores...',
    nullable: true,
  })
  fullText!: string | null;

  @ApiProperty({
    description: 'Abstract text - BUG FIX (Nov 19, 2025)',
    example: 'This study investigates the impact of...',
    nullable: true,
  })
  abstract!: string | null;
}

/**
 * Response DTO for GET /library/:paperId
 *
 * Wraps paper details in consistent response structure.
 */
export class GetPaperResponseDto {
  @ApiProperty({
    description: 'Paper details with full-text status',
    type: PaperDetailsDto,
  })
  paper!: PaperDetailsDto;
}
