/**
 * Phase 10.113 Week 3: Hierarchical Theme Extraction Types
 *
 * Type definitions for multi-level theme discovery:
 * - Level 1: Meta-themes (5-8 high-level clusters)
 * - Level 2: Sub-themes (3-5 per meta-theme)
 *
 * Netflix-Grade Standards:
 * - Zero `any` types
 * - Strict readonly where applicable
 * - Comprehensive JSDoc documentation
 * - Type guards included
 *
 * @author Phase 10.113 - Hierarchical Theme Extraction
 * @date December 2025
 */

// ============================================================================
// CORE HIERARCHICAL THEME TYPES
// ============================================================================

/**
 * Paper reference for hierarchical clustering
 * Minimal interface for papers in theme clusters
 */
export interface HierarchicalPaperRef {
  /** Unique paper identifier */
  readonly id: string;
  /** Paper title */
  readonly title: string;
  /** Paper abstract (optional) */
  readonly abstract?: string;
  /** Theme-Fit score (0-1) if available */
  readonly themeFitScore?: number;
}

/**
 * Level 1: Meta-Theme
 * High-level thematic cluster containing 5-8 meta-themes
 *
 * Phase 10.113 Specification:
 * - Cluster papers by semantic similarity
 * - Identify 5-8 meta-themes
 * - Map paper -> meta-theme relationships
 */
export interface MetaTheme {
  /** Unique identifier (UUID v4) */
  readonly id: string;

  /** Human-readable label generated by AI */
  readonly label: string;

  /** Detailed description of the meta-theme */
  readonly description: string;

  /** Paper IDs belonging to this meta-theme cluster */
  readonly paperIds: readonly string[];

  /** Representative paper IDs (most central to centroid) */
  readonly representativePaperIds: readonly string[];

  /** Centroid embedding vector (cluster center) */
  readonly centroidEmbedding: readonly number[];

  /** Coherence score: How well papers fit together (0-1) */
  readonly coherenceScore: number;

  /** Relative weight/importance of this meta-theme (0-1) */
  readonly weight: number;

  /** Keywords extracted from papers in this cluster */
  readonly keywords: readonly string[];

  /** Average Theme-Fit score of papers in cluster */
  readonly avgThemeFitScore: number;

  /** Sub-themes within this meta-theme (populated in Level 2) */
  readonly subThemes: readonly SubTheme[];

  /** Controversy level detected in this meta-theme (0-1) */
  readonly controversyLevel: number;

  /** Creation timestamp */
  readonly createdAt: Date;
}

/**
 * Level 2: Sub-Theme
 * Granular theme within a meta-theme (3-5 per meta-theme)
 *
 * Phase 10.113 Specification:
 * - Drill into each meta-theme cluster
 * - Extract 3-5 sub-themes per meta-theme
 * - Identify key papers for each sub-theme
 */
export interface SubTheme {
  /** Unique identifier (UUID v4) */
  readonly id: string;

  /** Parent meta-theme ID */
  readonly parentMetaThemeId: string;

  /** Human-readable label */
  readonly label: string;

  /** Detailed description */
  readonly description: string;

  /** Paper IDs in this sub-theme */
  readonly paperIds: readonly string[];

  /** Key/representative paper IDs */
  readonly keyPaperIds: readonly string[];

  /** Keywords specific to this sub-theme */
  readonly keywords: readonly string[];

  /** Relative weight within parent meta-theme (0-1) */
  readonly weight: number;

  /** Controversy level (0-1) */
  readonly controversyLevel: number;

  /** Centroid embedding for this sub-cluster */
  readonly centroidEmbedding: readonly number[];

  /** Coherence score (0-1) */
  readonly coherenceScore: number;
}

// ============================================================================
// HIERARCHICAL EXTRACTION CONFIGURATION
// ============================================================================

/**
 * Configuration for hierarchical theme extraction
 */
export interface HierarchicalExtractionConfig {
  /** Minimum number of meta-themes to extract */
  readonly minMetaThemes: number;

  /** Maximum number of meta-themes to extract */
  readonly maxMetaThemes: number;

  /** Minimum sub-themes per meta-theme */
  readonly minSubThemesPerMeta: number;

  /** Maximum sub-themes per meta-theme */
  readonly maxSubThemesPerMeta: number;

  /** Minimum papers required per cluster */
  readonly minPapersPerCluster: number;

  /** Coherence threshold for accepting clusters (0-1) */
  readonly coherenceThreshold: number;

  /** Use AI for label generation */
  readonly useAILabeling: boolean;

  /** Include controversy detection */
  readonly detectControversies: boolean;
}

/**
 * Default configuration for hierarchical extraction
 * Based on Phase 10.113 specifications
 */
export const DEFAULT_HIERARCHICAL_CONFIG: Readonly<HierarchicalExtractionConfig> = {
  minMetaThemes: 5,
  maxMetaThemes: 8,
  minSubThemesPerMeta: 3,
  maxSubThemesPerMeta: 5,
  minPapersPerCluster: 2,
  coherenceThreshold: 0.3,
  useAILabeling: true,
  detectControversies: true,
} as const;

/**
 * Paper count constraints for hierarchical extraction
 * - MIN: Minimum papers needed for meaningful k-means clustering
 * - MAX: Aligned with THEMATIZATION_TIERS maximum (300 papers)
 */
export const HIERARCHICAL_PAPER_LIMITS = {
  MIN_PAPERS: 10,
  MAX_PAPERS: 300,
} as const;

// ============================================================================
// EXTRACTION RESULT TYPES
// ============================================================================

/**
 * Result from hierarchical theme extraction
 */
export interface HierarchicalExtractionResult {
  /** Extracted meta-themes with sub-themes */
  readonly metaThemes: readonly MetaTheme[];

  /** Total papers processed */
  readonly totalPapers: number;

  /** Papers successfully clustered */
  readonly clusteredPapers: number;

  /** Papers that couldn't be assigned (orphaned) */
  readonly orphanedPaperIds: readonly string[];

  /** Quality metrics for the extraction */
  readonly qualityMetrics: HierarchicalQualityMetrics;

  /** Processing time in milliseconds */
  readonly processingTimeMs: number;

  /** Configuration used for extraction */
  readonly config: HierarchicalExtractionConfig;

  /** Extraction timestamp */
  readonly timestamp: Date;
}

/**
 * Quality metrics for hierarchical extraction
 */
export interface HierarchicalQualityMetrics {
  /** Average coherence across all meta-themes */
  readonly avgMetaThemeCoherence: number;

  /** Average coherence across all sub-themes */
  readonly avgSubThemeCoherence: number;

  /** Davies-Bouldin index for meta-theme clustering (lower = better) */
  readonly metaThemeDaviesBouldin: number;

  /** Silhouette score for meta-theme clustering (-1 to 1, higher = better) */
  readonly metaThemeSilhouette: number;

  /** Percentage of papers successfully clustered */
  readonly clusterCoverage: number;

  /** Average papers per meta-theme */
  readonly avgPapersPerMetaTheme: number;

  /** Average sub-themes per meta-theme */
  readonly avgSubThemesPerMetaTheme: number;

  /** Theme diversity score (0-1, higher = more diverse themes) */
  readonly themeDiversity: number;
}

// ============================================================================
// PROGRESS TRACKING TYPES
// ============================================================================

/**
 * Progress callback for hierarchical extraction
 */
export type HierarchicalProgressCallback = (
  stage: HierarchicalExtractionStage,
  progress: number,
  message: string,
) => void;

/**
 * Stages of hierarchical extraction
 */
export enum HierarchicalExtractionStage {
  INITIALIZING = 'INITIALIZING',
  GENERATING_EMBEDDINGS = 'GENERATING_EMBEDDINGS',
  META_THEME_CLUSTERING = 'META_THEME_CLUSTERING',
  META_THEME_LABELING = 'META_THEME_LABELING',
  SUB_THEME_EXTRACTION = 'SUB_THEME_EXTRACTION',
  SUB_THEME_LABELING = 'SUB_THEME_LABELING',
  QUALITY_ANALYSIS = 'QUALITY_ANALYSIS',
  COMPLETE = 'COMPLETE',
}

// ============================================================================
// INTERNAL CLUSTERING TYPES
// ============================================================================

/**
 * Internal paper representation with embedding
 */
export interface PaperWithEmbedding {
  readonly id: string;
  readonly title: string;
  readonly abstract: string;
  readonly embedding: readonly number[];
  readonly themeFitScore?: number;
}

/**
 * Intermediate cluster result (before labeling)
 */
export interface RawCluster {
  readonly paperIds: readonly string[];
  readonly centroid: readonly number[];
  readonly papers: readonly PaperWithEmbedding[];
}

// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard for MetaTheme
 */
export function isMetaTheme(obj: unknown): obj is MetaTheme {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'id' in obj &&
    'label' in obj &&
    'paperIds' in obj &&
    Array.isArray((obj as MetaTheme).paperIds) &&
    'subThemes' in obj &&
    Array.isArray((obj as MetaTheme).subThemes)
  );
}

/**
 * Type guard for SubTheme
 */
export function isSubTheme(obj: unknown): obj is SubTheme {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'id' in obj &&
    'parentMetaThemeId' in obj &&
    'label' in obj &&
    'paperIds' in obj &&
    Array.isArray((obj as SubTheme).paperIds)
  );
}

/**
 * Type guard for HierarchicalExtractionResult
 */
export function isHierarchicalExtractionResult(
  obj: unknown,
): obj is HierarchicalExtractionResult {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'metaThemes' in obj &&
    Array.isArray((obj as HierarchicalExtractionResult).metaThemes) &&
    'totalPapers' in obj &&
    'qualityMetrics' in obj
  );
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Paper input for hierarchical extraction
 * Accepts various paper formats with required fields
 */
export interface HierarchicalPaperInput {
  id: string;
  title: string;
  abstract?: string;
  themeFitScore?: number;
  keywords?: string[];
}

/**
 * Mutable version of MetaTheme for internal processing
 */
export interface MutableMetaTheme extends Omit<MetaTheme, 'subThemes' | 'paperIds' | 'representativePaperIds' | 'keywords' | 'centroidEmbedding'> {
  paperIds: string[];
  representativePaperIds: string[];
  keywords: string[];
  centroidEmbedding: number[];
  subThemes: SubTheme[];
}

/**
 * Mutable version of SubTheme for internal processing
 */
export interface MutableSubTheme extends Omit<SubTheme, 'paperIds' | 'keyPaperIds' | 'keywords' | 'centroidEmbedding'> {
  paperIds: string[];
  keyPaperIds: string[];
  keywords: string[];
  centroidEmbedding: number[];
}
