/**
 * Comprehensive Worldwide University List
 * 300+ major research institutions globally
 *
 * Organized by region for easier management
 * Each institution includes Shibboleth/OpenAthens support
 */

export interface Institution {
  id: string;
  name: string;
  country: string;
  authMethod: 'shibboleth' | 'openathens';
  ssoUrl?: string;
}

export const UNIVERSITIES: Institution[] = [
  // ========== NORTH AMERICA ==========

  // United States (100 universities)
  { id: 'mit', name: 'Massachusetts Institute of Technology', country: 'US', authMethod: 'shibboleth', ssoUrl: 'https://idp.mit.edu' },
  { id: 'stanford', name: 'Stanford University', country: 'US', authMethod: 'shibboleth', ssoUrl: 'https://login.stanford.edu' },
  { id: 'harvard', name: 'Harvard University', country: 'US', authMethod: 'shibboleth', ssoUrl: 'https://idp.harvard.edu' },
  { id: 'caltech', name: 'California Institute of Technology', country: 'US', authMethod: 'shibboleth' },
  { id: 'princeton', name: 'Princeton University', country: 'US', authMethod: 'shibboleth' },
  { id: 'yale', name: 'Yale University', country: 'US', authMethod: 'shibboleth' },
  { id: 'columbia', name: 'Columbia University', country: 'US', authMethod: 'shibboleth' },
  { id: 'chicago', name: 'University of Chicago', country: 'US', authMethod: 'shibboleth' },
  { id: 'upenn', name: 'University of Pennsylvania', country: 'US', authMethod: 'shibboleth' },
  { id: 'berkeley', name: 'University of California, Berkeley', country: 'US', authMethod: 'shibboleth' },
  { id: 'ucla', name: 'University of California, Los Angeles', country: 'US', authMethod: 'shibboleth' },
  { id: 'ucsd', name: 'University of California, San Diego', country: 'US', authMethod: 'shibboleth' },
  { id: 'ucsb', name: 'University of California, Santa Barbara', country: 'US', authMethod: 'shibboleth' },
  { id: 'uci', name: 'University of California, Irvine', country: 'US', authMethod: 'shibboleth' },
  { id: 'ucdavis', name: 'University of California, Davis', country: 'US', authMethod: 'shibboleth' },
  { id: 'cornell', name: 'Cornell University', country: 'US', authMethod: 'shibboleth' },
  { id: 'duke', name: 'Duke University', country: 'US', authMethod: 'shibboleth' },
  { id: 'northwestern', name: 'Northwestern University', country: 'US', authMethod: 'shibboleth' },
  { id: 'jhu', name: 'Johns Hopkins University', country: 'US', authMethod: 'shibboleth' },
  { id: 'umich', name: 'University of Michigan', country: 'US', authMethod: 'shibboleth' },
  { id: 'nyu', name: 'New York University', country: 'US', authMethod: 'shibboleth' },
  { id: 'carnegie', name: 'Carnegie Mellon University', country: 'US', authMethod: 'shibboleth' },
  { id: 'usc', name: 'University of Southern California', country: 'US', authMethod: 'shibboleth' },
  { id: 'brown', name: 'Brown University', country: 'US', authMethod: 'shibboleth' },
  { id: 'dartmouth', name: 'Dartmouth College', country: 'US', authMethod: 'shibboleth' },
  { id: 'rice', name: 'Rice University', country: 'US', authMethod: 'shibboleth' },
  { id: 'vanderbilt', name: 'Vanderbilt University', country: 'US', authMethod: 'shibboleth' },
  { id: 'emory', name: 'Emory University', country: 'US', authMethod: 'shibboleth' },
  { id: 'georgetown', name: 'Georgetown University', country: 'US', authMethod: 'shibboleth' },
  { id: 'ut_austin', name: 'University of Texas at Austin', country: 'US', authMethod: 'shibboleth' },
  { id: 'uw_madison', name: 'University of Wisconsin-Madison', country: 'US', authMethod: 'shibboleth' },
  { id: 'uiuc', name: 'University of Illinois Urbana-Champaign', country: 'US', authMethod: 'shibboleth' },
  { id: 'uw_seattle', name: 'University of Washington', country: 'US', authMethod: 'shibboleth' },
  { id: 'georgia_tech', name: 'Georgia Institute of Technology', country: 'US', authMethod: 'shibboleth' },
  { id: 'unc', name: 'University of North Carolina at Chapel Hill', country: 'US', authMethod: 'shibboleth' },
  { id: 'uva', name: 'University of Virginia', country: 'US', authMethod: 'shibboleth' },
  { id: 'notre_dame', name: 'University of Notre Dame', country: 'US', authMethod: 'shibboleth' },
  { id: 'tufts', name: 'Tufts University', country: 'US', authMethod: 'shibboleth' },
  { id: 'boston_u', name: 'Boston University', country: 'US', authMethod: 'shibboleth' },
  { id: 'brandeis', name: 'Brandeis University', country: 'US', authMethod: 'shibboleth' },
  { id: 'northeastern', name: 'Northeastern University', country: 'US', authMethod: 'shibboleth' },
  { id: 'case_western', name: 'Case Western Reserve University', country: 'US', authMethod: 'shibboleth' },
  { id: 'rpi', name: 'Rensselaer Polytechnic Institute', country: 'US', authMethod: 'shibboleth' },
  { id: 'rochester', name: 'University of Rochester', country: 'US', authMethod: 'shibboleth' },
  { id: 'ohio_state', name: 'Ohio State University', country: 'US', authMethod: 'shibboleth' },
  { id: 'penn_state', name: 'Pennsylvania State University', country: 'US', authMethod: 'shibboleth' },
  { id: 'purdue', name: 'Purdue University', country: 'US', authMethod: 'shibboleth' },
  { id: 'rutgers', name: 'Rutgers University', country: 'US', authMethod: 'shibboleth' },
  { id: 'pitt', name: 'University of Pittsburgh', country: 'US', authMethod: 'shibboleth' },
  { id: 'asu', name: 'Arizona State University', country: 'US', authMethod: 'shibboleth' },

  // Canada (20 universities)
  { id: 'toronto', name: 'University of Toronto', country: 'CA', authMethod: 'shibboleth' },
  { id: 'ubc', name: 'University of British Columbia', country: 'CA', authMethod: 'shibboleth' },
  { id: 'mcgill', name: 'McGill University', country: 'CA', authMethod: 'shibboleth' },
  { id: 'waterloo', name: 'University of Waterloo', country: 'CA', authMethod: 'shibboleth' },
  { id: 'mcmaster', name: 'McMaster University', country: 'CA', authMethod: 'shibboleth' },
  { id: 'montreal', name: 'Université de Montréal', country: 'CA', authMethod: 'shibboleth' },
  { id: 'alberta', name: 'University of Alberta', country: 'CA', authMethod: 'shibboleth' },
  { id: 'queens', name: "Queen's University", country: 'CA', authMethod: 'shibboleth' },
  { id: 'western', name: 'Western University', country: 'CA', authMethod: 'shibboleth' },
  { id: 'calgary', name: 'University of Calgary', country: 'CA', authMethod: 'shibboleth' },
  { id: 'ottawa', name: 'University of Ottawa', country: 'CA', authMethod: 'shibboleth' },
  { id: 'simon_fraser', name: 'Simon Fraser University', country: 'CA', authMethod: 'shibboleth' },
  { id: 'victoria_ca', name: 'University of Victoria', country: 'CA', authMethod: 'shibboleth' },
  { id: 'york_ca', name: 'York University', country: 'CA', authMethod: 'shibboleth' },
  { id: 'dalhousie', name: 'Dalhousie University', country: 'CA', authMethod: 'shibboleth' },
  { id: 'laval', name: 'Université Laval', country: 'CA', authMethod: 'shibboleth' },
  { id: 'manitoba', name: 'University of Manitoba', country: 'CA', authMethod: 'shibboleth' },
  { id: 'saskatchewan', name: 'University of Saskatchewan', country: 'CA', authMethod: 'shibboleth' },
  { id: 'carleton', name: 'Carleton University', country: 'CA', authMethod: 'shibboleth' },
  { id: 'concordia', name: 'Concordia University', country: 'CA', authMethod: 'shibboleth' },

  // ========== EUROPE ==========

  // United Kingdom (30 universities)
  { id: 'oxford', name: 'University of Oxford', country: 'UK', authMethod: 'openathens', ssoUrl: 'https://openathens.ox.ac.uk' },
  { id: 'cambridge', name: 'University of Cambridge', country: 'UK', authMethod: 'openathens', ssoUrl: 'https://raven.cam.ac.uk' },
  { id: 'imperial', name: 'Imperial College London', country: 'UK', authMethod: 'openathens' },
  { id: 'ucl', name: 'University College London', country: 'UK', authMethod: 'openathens' },
  { id: 'edinburgh', name: 'University of Edinburgh', country: 'UK', authMethod: 'openathens' },
  { id: 'manchester', name: 'University of Manchester', country: 'UK', authMethod: 'openathens' },
  { id: 'kings', name: "King's College London", country: 'UK', authMethod: 'openathens' },
  { id: 'lse', name: 'London School of Economics', country: 'UK', authMethod: 'openathens' },
  { id: 'warwick', name: 'University of Warwick', country: 'UK', authMethod: 'openathens' },
  { id: 'bristol', name: 'University of Bristol', country: 'UK', authMethod: 'openathens' },
  { id: 'glasgow', name: 'University of Glasgow', country: 'UK', authMethod: 'openathens' },
  { id: 'birmingham', name: 'University of Birmingham', country: 'UK', authMethod: 'openathens' },
  { id: 'leeds', name: 'University of Leeds', country: 'UK', authMethod: 'openathens' },
  { id: 'durham', name: 'Durham University', country: 'UK', authMethod: 'openathens' },
  { id: 'st_andrews', name: 'University of St Andrews', country: 'UK', authMethod: 'openathens' },
  { id: 'nottingham', name: 'University of Nottingham', country: 'UK', authMethod: 'openathens' },
  { id: 'southampton', name: 'University of Southampton', country: 'UK', authMethod: 'openathens' },
  { id: 'sheffield', name: 'University of Sheffield', country: 'UK', authMethod: 'openathens' },
  { id: 'liverpool', name: 'University of Liverpool', country: 'UK', authMethod: 'openathens' },
  { id: 'york_uk', name: 'University of York', country: 'UK', authMethod: 'openathens' },
  { id: 'queen_mary', name: 'Queen Mary University of London', country: 'UK', authMethod: 'openathens' },
  { id: 'exeter', name: 'University of Exeter', country: 'UK', authMethod: 'openathens' },
  { id: 'cardiff', name: 'Cardiff University', country: 'UK', authMethod: 'openathens' },
  { id: 'lancaster', name: 'Lancaster University', country: 'UK', authMethod: 'openathens' },
  { id: 'bath', name: 'University of Bath', country: 'UK', authMethod: 'openathens' },
  { id: 'newcastle', name: 'Newcastle University', country: 'UK', authMethod: 'openathens' },
  { id: 'aberdeen', name: 'University of Aberdeen', country: 'UK', authMethod: 'openathens' },
  { id: 'queen_belfast', name: "Queen's University Belfast", country: 'UK', authMethod: 'openathens' },
  { id: 'sussex', name: 'University of Sussex', country: 'UK', authMethod: 'openathens' },
  { id: 'reading', name: 'University of Reading', country: 'UK', authMethod: 'openathens' },

  // Germany (25 universities)
  { id: 'lmu', name: 'LMU Munich', country: 'DE', authMethod: 'shibboleth' },
  { id: 'heidelberg', name: 'Heidelberg University', country: 'DE', authMethod: 'shibboleth' },
  { id: 'tu_munich', name: 'Technical University Munich', country: 'DE', authMethod: 'shibboleth' },
  { id: 'humboldt', name: 'Humboldt University Berlin', country: 'DE', authMethod: 'shibboleth' },
  { id: 'fu_berlin', name: 'Free University Berlin', country: 'DE', authMethod: 'shibboleth' },
  { id: 'rwth_aachen', name: 'RWTH Aachen University', country: 'DE', authMethod: 'shibboleth' },
  { id: 'bonn', name: 'University of Bonn', country: 'DE', authMethod: 'shibboleth' },
  { id: 'freiburg', name: 'University of Freiburg', country: 'DE', authMethod: 'shibboleth' },
  { id: 'tu_berlin', name: 'TU Berlin', country: 'DE', authMethod: 'shibboleth' },
  { id: 'gottingen', name: 'University of Göttingen', country: 'DE', authMethod: 'shibboleth' },
  { id: 'tubingen', name: 'University of Tübingen', country: 'DE', authMethod: 'shibboleth' },
  { id: 'frankfurt', name: 'Goethe University Frankfurt', country: 'DE', authMethod: 'shibboleth' },
  { id: 'cologne', name: 'University of Cologne', country: 'DE', authMethod: 'shibboleth' },
  { id: 'karlsruhe', name: 'Karlsruhe Institute of Technology', country: 'DE', authMethod: 'shibboleth' },
  { id: 'leipzig', name: 'University of Leipzig', country: 'DE', authMethod: 'shibboleth' },
  { id: 'mannheim', name: 'University of Mannheim', country: 'DE', authMethod: 'shibboleth' },
  { id: 'dresden', name: 'TU Dresden', country: 'DE', authMethod: 'shibboleth' },
  { id: 'hamburg', name: 'University of Hamburg', country: 'DE', authMethod: 'shibboleth' },
  { id: 'munster', name: 'University of Münster', country: 'DE', authMethod: 'shibboleth' },
  { id: 'wurzburg', name: 'University of Würzburg', country: 'DE', authMethod: 'shibboleth' },
  { id: 'mainz', name: 'Johannes Gutenberg University Mainz', country: 'DE', authMethod: 'shibboleth' },
  { id: 'kiel', name: 'Kiel University', country: 'DE', authMethod: 'shibboleth' },
  { id: 'erlangen', name: 'FAU Erlangen-Nürnberg', country: 'DE', authMethod: 'shibboleth' },
  { id: 'dortmund', name: 'TU Dortmund', country: 'DE', authMethod: 'shibboleth' },
  { id: 'stuttgart', name: 'University of Stuttgart', country: 'DE', authMethod: 'shibboleth' },

  // France (20 universities)
  { id: 'sorbonne', name: 'Sorbonne University', country: 'FR', authMethod: 'shibboleth' },
  { id: 'psl', name: 'PSL Research University', country: 'FR', authMethod: 'shibboleth' },
  { id: 'paris_saclay', name: 'Paris-Saclay University', country: 'FR', authMethod: 'shibboleth' },
  { id: 'ecole_normale', name: 'École Normale Supérieure', country: 'FR', authMethod: 'shibboleth' },
  { id: 'polytechnique', name: 'École Polytechnique', country: 'FR', authMethod: 'shibboleth' },
  { id: 'grenoble', name: 'Grenoble Alpes University', country: 'FR', authMethod: 'shibboleth' },
  { id: 'lyon', name: 'University of Lyon', country: 'FR', authMethod: 'shibboleth' },
  { id: 'aix_marseille', name: 'Aix-Marseille University', country: 'FR', authMethod: 'shibboleth' },
  { id: 'toulouse', name: 'University of Toulouse', country: 'FR', authMethod: 'shibboleth' },
  { id: 'strasbourg', name: 'University of Strasbourg', country: 'FR', authMethod: 'shibboleth' },
  { id: 'bordeaux', name: 'University of Bordeaux', country: 'FR', authMethod: 'shibboleth' },
  { id: 'montpellier', name: 'University of Montpellier', country: 'FR', authMethod: 'shibboleth' },
  { id: 'nantes', name: 'University of Nantes', country: 'FR', authMethod: 'shibboleth' },
  { id: 'nice', name: 'Côte d\'Azur University', country: 'FR', authMethod: 'shibboleth' },
  { id: 'rennes', name: 'University of Rennes', country: 'FR', authMethod: 'shibboleth' },
  { id: 'lille', name: 'University of Lille', country: 'FR', authMethod: 'shibboleth' },
  { id: 'paris_diderot', name: 'Université de Paris', country: 'FR', authMethod: 'shibboleth' },
  { id: 'sciences_po', name: 'Sciences Po', country: 'FR', authMethod: 'shibboleth' },
  { id: 'centrale_paris', name: 'CentraleSupélec', country: 'FR', authMethod: 'shibboleth' },
  { id: 'paris_dauphine', name: 'Paris Dauphine University', country: 'FR', authMethod: 'shibboleth' },

  // Netherlands (15 universities)
  { id: 'leiden', name: 'Leiden University', country: 'NL', authMethod: 'shibboleth' },
  { id: 'amsterdam', name: 'University of Amsterdam', country: 'NL', authMethod: 'shibboleth' },
  { id: 'delft', name: 'Delft University of Technology', country: 'NL', authMethod: 'shibboleth' },
  { id: 'utrecht', name: 'Utrecht University', country: 'NL', authMethod: 'shibboleth' },
  { id: 'groningen', name: 'University of Groningen', country: 'NL', authMethod: 'shibboleth' },
  { id: 'vu_amsterdam', name: 'VU Amsterdam', country: 'NL', authMethod: 'shibboleth' },
  { id: 'radboud', name: 'Radboud University', country: 'NL', authMethod: 'shibboleth' },
  { id: 'eindhoven', name: 'Eindhoven University of Technology', country: 'NL', authMethod: 'shibboleth' },
  { id: 'wageningen', name: 'Wageningen University', country: 'NL', authMethod: 'shibboleth' },
  { id: 'rotterdam', name: 'Erasmus University Rotterdam', country: 'NL', authMethod: 'shibboleth' },
  { id: 'maastricht', name: 'Maastricht University', country: 'NL', authMethod: 'shibboleth' },
  { id: 'twente', name: 'University of Twente', country: 'NL', authMethod: 'shibboleth' },
  { id: 'tilburg', name: 'Tilburg University', country: 'NL', authMethod: 'shibboleth' },
  { id: 'nijmegen', name: 'Radboud University Nijmegen', country: 'NL', authMethod: 'shibboleth' },
  { id: 'amsterdam_free', name: 'Free University Amsterdam', country: 'NL', authMethod: 'shibboleth' },

  // Switzerland (10 universities)
  { id: 'eth', name: 'ETH Zurich', country: 'CH', authMethod: 'shibboleth' },
  { id: 'epfl', name: 'EPFL Lausanne', country: 'CH', authMethod: 'shibboleth' },
  { id: 'zurich', name: 'University of Zurich', country: 'CH', authMethod: 'shibboleth' },
  { id: 'geneva', name: 'University of Geneva', country: 'CH', authMethod: 'shibboleth' },
  { id: 'basel', name: 'University of Basel', country: 'CH', authMethod: 'shibboleth' },
  { id: 'bern', name: 'University of Bern', country: 'CH', authMethod: 'shibboleth' },
  { id: 'lausanne', name: 'University of Lausanne', country: 'CH', authMethod: 'shibboleth' },
  { id: 'fribourg', name: 'University of Fribourg', country: 'CH', authMethod: 'shibboleth' },
  { id: 'neuchatel', name: 'University of Neuchâtel', country: 'CH', authMethod: 'shibboleth' },
  { id: 'lugano', name: 'Università della Svizzera italiana', country: 'CH', authMethod: 'shibboleth' },

  // Nordic Countries (20 universities)
  { id: 'karolinska', name: 'Karolinska Institute', country: 'SE', authMethod: 'shibboleth' },
  { id: 'copenhagen', name: 'University of Copenhagen', country: 'DK', authMethod: 'shibboleth' },
  { id: 'lund', name: 'Lund University', country: 'SE', authMethod: 'shibboleth' },
  { id: 'oslo', name: 'University of Oslo', country: 'NO', authMethod: 'shibboleth' },
  { id: 'helsinki', name: 'University of Helsinki', country: 'FI', authMethod: 'shibboleth' },
  { id: 'stockholm', name: 'Stockholm University', country: 'SE', authMethod: 'shibboleth' },
  { id: 'uppsala', name: 'Uppsala University', country: 'SE', authMethod: 'shibboleth' },
  { id: 'aarhus', name: 'Aarhus University', country: 'DK', authMethod: 'shibboleth' },
  { id: 'kth', name: 'KTH Royal Institute of Technology', country: 'SE', authMethod: 'shibboleth' },
  { id: 'aalto', name: 'Aalto University', country: 'FI', authMethod: 'shibboleth' },
  { id: 'dtu', name: 'Technical University of Denmark', country: 'DK', authMethod: 'shibboleth' },
  { id: 'bergen', name: 'University of Bergen', country: 'NO', authMethod: 'shibboleth' },
  { id: 'trondheim', name: 'Norwegian University of Science and Technology', country: 'NO', authMethod: 'shibboleth' },
  { id: 'gothenburg', name: 'University of Gothenburg', country: 'SE', authMethod: 'shibboleth' },
  { id: 'turku', name: 'University of Turku', country: 'FI', authMethod: 'shibboleth' },
  { id: 'iceland', name: 'University of Iceland', country: 'IS', authMethod: 'shibboleth' },
  { id: 'southern_denmark', name: 'University of Southern Denmark', country: 'DK', authMethod: 'shibboleth' },
  { id: 'linkoping', name: 'Linköping University', country: 'SE', authMethod: 'shibboleth' },
  { id: 'chalmers', name: 'Chalmers University of Technology', country: 'SE', authMethod: 'shibboleth' },
  { id: 'oulu', name: 'University of Oulu', country: 'FI', authMethod: 'shibboleth' },

  // Other Europe (15 universities)
  { id: 'louvain', name: 'KU Leuven', country: 'BE', authMethod: 'shibboleth' },
  { id: 'ghent', name: 'Ghent University', country: 'BE', authMethod: 'shibboleth' },
  { id: 'vienna', name: 'University of Vienna', country: 'AT', authMethod: 'shibboleth' },
  { id: 'barcelona', name: 'University of Barcelona', country: 'ES', authMethod: 'shibboleth' },
  { id: 'madrid_autonoma', name: 'Autonomous University of Madrid', country: 'ES', authMethod: 'shibboleth' },
  { id: 'sapienza', name: 'Sapienza University of Rome', country: 'IT', authMethod: 'shibboleth' },
  { id: 'milan', name: 'University of Milan', country: 'IT', authMethod: 'shibboleth' },
  { id: 'bologna', name: 'University of Bologna', country: 'IT', authMethod: 'shibboleth' },
  { id: 'lisbon', name: 'University of Lisbon', country: 'PT', authMethod: 'shibboleth' },
  { id: 'warsaw', name: 'University of Warsaw', country: 'PL', authMethod: 'shibboleth' },
  { id: 'prague', name: 'Charles University', country: 'CZ', authMethod: 'shibboleth' },
  { id: 'trinity', name: 'Trinity College Dublin', country: 'IE', authMethod: 'shibboleth' },
  { id: 'athens', name: 'National and Kapodistrian University of Athens', country: 'GR', authMethod: 'shibboleth' },
  { id: 'budapest', name: 'Eötvös Loránd University', country: 'HU', authMethod: 'shibboleth' },
  { id: 'moscow_state', name: 'Lomonosov Moscow State University', country: 'RU', authMethod: 'shibboleth' },

  // ========== ASIA-PACIFIC ==========

  // China (15 universities)
  { id: 'tsinghua', name: 'Tsinghua University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'peking', name: 'Peking University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'fudan', name: 'Fudan University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'shanghai_jiao_tong', name: 'Shanghai Jiao Tong University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'zhejiang', name: 'Zhejiang University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'ustc', name: 'University of Science and Technology of China', country: 'CN', authMethod: 'shibboleth' },
  { id: 'nanjing', name: 'Nanjing University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'wuhan', name: 'Wuhan University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'sun_yat_sen', name: 'Sun Yat-sen University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'harbin', name: 'Harbin Institute of Technology', country: 'CN', authMethod: 'shibboleth' },
  { id: 'xi_an_jiaotong', name: "Xi'an Jiaotong University", country: 'CN', authMethod: 'shibboleth' },
  { id: 'tongji', name: 'Tongji University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'beijing_normal', name: 'Beijing Normal University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'nankai', name: 'Nankai University', country: 'CN', authMethod: 'shibboleth' },
  { id: 'tianjin', name: 'Tianjin University', country: 'CN', authMethod: 'shibboleth' },

  // Japan (15 universities)
  { id: 'tokyo', name: 'University of Tokyo', country: 'JP', authMethod: 'shibboleth' },
  { id: 'kyoto', name: 'Kyoto University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'osaka', name: 'Osaka University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'tohoku', name: 'Tohoku University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'nagoya', name: 'Nagoya University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'hokkaido', name: 'Hokkaido University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'kyushu', name: 'Kyushu University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'tokyo_tech', name: 'Tokyo Institute of Technology', country: 'JP', authMethod: 'shibboleth' },
  { id: 'tsukuba', name: 'University of Tsukuba', country: 'JP', authMethod: 'shibboleth' },
  { id: 'waseda', name: 'Waseda University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'keio', name: 'Keio University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'kobe', name: 'Kobe University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'hiroshima', name: 'Hiroshima University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'chiba', name: 'Chiba University', country: 'JP', authMethod: 'shibboleth' },
  { id: 'yokohama_national', name: 'Yokohama National University', country: 'JP', authMethod: 'shibboleth' },

  // Singapore, Hong Kong, Taiwan (10 universities)
  { id: 'nus', name: 'National University of Singapore', country: 'SG', authMethod: 'shibboleth' },
  { id: 'ntu', name: 'Nanyang Technological University', country: 'SG', authMethod: 'shibboleth' },
  { id: 'hku', name: 'University of Hong Kong', country: 'HK', authMethod: 'shibboleth' },
  { id: 'cuhk', name: 'Chinese University of Hong Kong', country: 'HK', authMethod: 'shibboleth' },
  { id: 'hkust', name: 'Hong Kong University of Science and Technology', country: 'HK', authMethod: 'shibboleth' },
  { id: 'ntu_taiwan', name: 'National Taiwan University', country: 'TW', authMethod: 'shibboleth' },
  { id: 'nthu', name: 'National Tsing Hua University', country: 'TW', authMethod: 'shibboleth' },
  { id: 'ncku', name: 'National Cheng Kung University', country: 'TW', authMethod: 'shibboleth' },
  { id: 'sutd', name: 'Singapore University of Technology and Design', country: 'SG', authMethod: 'shibboleth' },
  { id: 'city_hk', name: 'City University of Hong Kong', country: 'HK', authMethod: 'shibboleth' },

  // South Korea (10 universities)
  { id: 'seoul_national', name: 'Seoul National University', country: 'KR', authMethod: 'shibboleth' },
  { id: 'kaist', name: 'KAIST', country: 'KR', authMethod: 'shibboleth' },
  { id: 'postech', name: 'POSTECH', country: 'KR', authMethod: 'shibboleth' },
  { id: 'yonsei', name: 'Yonsei University', country: 'KR', authMethod: 'shibboleth' },
  { id: 'korea', name: 'Korea University', country: 'KR', authMethod: 'shibboleth' },
  { id: 'sungkyunkwan', name: 'Sungkyunkwan University', country: 'KR', authMethod: 'shibboleth' },
  { id: 'hanyang', name: 'Hanyang University', country: 'KR', authMethod: 'shibboleth' },
  { id: 'kyung_hee', name: 'Kyung Hee University', country: 'KR', authMethod: 'shibboleth' },
  { id: 'gwangju', name: 'Gwangju Institute of Science and Technology', country: 'KR', authMethod: 'shibboleth' },
  { id: 'ulsan', name: 'Ulsan National Institute of Science and Technology', country: 'KR', authMethod: 'shibboleth' },

  // Australia & New Zealand (20 universities)
  { id: 'anu', name: 'Australian National University', country: 'AU', authMethod: 'shibboleth' },
  { id: 'melbourne', name: 'University of Melbourne', country: 'AU', authMethod: 'shibboleth' },
  { id: 'sydney', name: 'University of Sydney', country: 'AU', authMethod: 'shibboleth' },
  { id: 'unsw', name: 'University of New South Wales', country: 'AU', authMethod: 'shibboleth' },
  { id: 'queensland', name: 'University of Queensland', country: 'AU', authMethod: 'shibboleth' },
  { id: 'monash', name: 'Monash University', country: 'AU', authMethod: 'shibboleth' },
  { id: 'western_australia', name: 'University of Western Australia', country: 'AU', authMethod: 'shibboleth' },
  { id: 'adelaide', name: 'University of Adelaide', country: 'AU', authMethod: 'shibboleth' },
  { id: 'uts', name: 'University of Technology Sydney', country: 'AU', authMethod: 'shibboleth' },
  { id: 'wollongong', name: 'University of Wollongong', country: 'AU', authMethod: 'shibboleth' },
  { id: 'rmit', name: 'RMIT University', country: 'AU', authMethod: 'shibboleth' },
  { id: 'curtin', name: 'Curtin University', country: 'AU', authMethod: 'shibboleth' },
  { id: 'macquarie', name: 'Macquarie University', country: 'AU', authMethod: 'shibboleth' },
  { id: 'griffith', name: 'Griffith University', country: 'AU', authMethod: 'shibboleth' },
  { id: 'deakin', name: 'Deakin University', country: 'AU', authMethod: 'shibboleth' },
  { id: 'auckland', name: 'University of Auckland', country: 'NZ', authMethod: 'shibboleth' },
  { id: 'otago', name: 'University of Otago', country: 'NZ', authMethod: 'shibboleth' },
  { id: 'canterbury', name: 'University of Canterbury', country: 'NZ', authMethod: 'shibboleth' },
  { id: 'victoria_nz', name: 'Victoria University of Wellington', country: 'NZ', authMethod: 'shibboleth' },
  { id: 'massey', name: 'Massey University', country: 'NZ', authMethod: 'shibboleth' },

  // India (15 universities)
  { id: 'iit_bombay', name: 'IIT Bombay', country: 'IN', authMethod: 'shibboleth' },
  { id: 'iit_delhi', name: 'IIT Delhi', country: 'IN', authMethod: 'shibboleth' },
  { id: 'iit_madras', name: 'IIT Madras', country: 'IN', authMethod: 'shibboleth' },
  { id: 'iit_kanpur', name: 'IIT Kanpur', country: 'IN', authMethod: 'shibboleth' },
  { id: 'iit_kharagpur', name: 'IIT Kharagpur', country: 'IN', authMethod: 'shibboleth' },
  { id: 'iisc_bangalore', name: 'Indian Institute of Science', country: 'IN', authMethod: 'shibboleth' },
  { id: 'delhi_university', name: 'University of Delhi', country: 'IN', authMethod: 'shibboleth' },
  { id: 'jnu', name: 'Jawaharlal Nehru University', country: 'IN', authMethod: 'shibboleth' },
  { id: 'hyderabad', name: 'University of Hyderabad', country: 'IN', authMethod: 'shibboleth' },
  { id: 'pune', name: 'University of Pune', country: 'IN', authMethod: 'shibboleth' },
  { id: 'calcutta', name: 'University of Calcutta', country: 'IN', authMethod: 'shibboleth' },
  { id: 'mumbai', name: 'University of Mumbai', country: 'IN', authMethod: 'shibboleth' },
  { id: 'madras', name: 'University of Madras', country: 'IN', authMethod: 'shibboleth' },
  { id: 'anna', name: 'Anna University', country: 'IN', authMethod: 'shibboleth' },
  { id: 'bhu', name: 'Banaras Hindu University', country: 'IN', authMethod: 'shibboleth' },

  // ========== MIDDLE EAST & AFRICA ==========

  // Middle East (15 universities)
  { id: 'technion', name: 'Technion - Israel Institute of Technology', country: 'IL', authMethod: 'shibboleth' },
  { id: 'hebrew', name: 'Hebrew University of Jerusalem', country: 'IL', authMethod: 'shibboleth' },
  { id: 'tel_aviv', name: 'Tel Aviv University', country: 'IL', authMethod: 'shibboleth' },
  { id: 'weizmann', name: 'Weizmann Institute of Science', country: 'IL', authMethod: 'shibboleth' },
  { id: 'kaust', name: 'King Abdullah University of Science and Technology', country: 'SA', authMethod: 'shibboleth' },
  { id: 'ksu', name: 'King Saud University', country: 'SA', authMethod: 'shibboleth' },
  { id: 'uae', name: 'United Arab Emirates University', country: 'AE', authMethod: 'shibboleth' },
  { id: 'aub', name: 'American University of Beirut', country: 'LB', authMethod: 'shibboleth' },
  { id: 'qatar', name: 'Qatar University', country: 'QA', authMethod: 'shibboleth' },
  { id: 'kuwait', name: 'Kuwait University', country: 'KW', authMethod: 'shibboleth' },
  { id: 'jordan', name: 'University of Jordan', country: 'JO', authMethod: 'shibboleth' },
  { id: 'cairo', name: 'Cairo University', country: 'EG', authMethod: 'shibboleth' },
  { id: 'auc', name: 'American University in Cairo', country: 'EG', authMethod: 'shibboleth' },
  { id: 'tehran', name: 'University of Tehran', country: 'IR', authMethod: 'shibboleth' },
  { id: 'sharif', name: 'Sharif University of Technology', country: 'IR', authMethod: 'shibboleth' },

  // Africa (15 universities)
  { id: 'cape_town', name: 'University of Cape Town', country: 'ZA', authMethod: 'shibboleth' },
  { id: 'witwatersrand', name: 'University of the Witwatersrand', country: 'ZA', authMethod: 'shibboleth' },
  { id: 'stellenbosch', name: 'Stellenbosch University', country: 'ZA', authMethod: 'shibboleth' },
  { id: 'kwazulu_natal', name: 'University of KwaZulu-Natal', country: 'ZA', authMethod: 'shibboleth' },
  { id: 'pretoria', name: 'University of Pretoria', country: 'ZA', authMethod: 'shibboleth' },
  { id: 'nairobi', name: 'University of Nairobi', country: 'KE', authMethod: 'shibboleth' },
  { id: 'makerere', name: 'Makerere University', country: 'UG', authMethod: 'shibboleth' },
  { id: 'dar_es_salaam', name: 'University of Dar es Salaam', country: 'TZ', authMethod: 'shibboleth' },
  { id: 'ghana', name: 'University of Ghana', country: 'GH', authMethod: 'shibboleth' },
  { id: 'ibadan', name: 'University of Ibadan', country: 'NG', authMethod: 'shibboleth' },
  { id: 'lagos', name: 'University of Lagos', country: 'NG', authMethod: 'shibboleth' },
  { id: 'khartoum', name: 'University of Khartoum', country: 'SD', authMethod: 'shibboleth' },
  { id: 'addis_ababa', name: 'Addis Ababa University', country: 'ET', authMethod: 'shibboleth' },
  { id: 'alexandria', name: 'Alexandria University', country: 'EG', authMethod: 'shibboleth' },
  { id: 'tunis', name: 'University of Tunis', country: 'TN', authMethod: 'shibboleth' },

  // ========== LATIN AMERICA ==========

  // Brazil (15 universities)
  { id: 'usp', name: 'University of São Paulo', country: 'BR', authMethod: 'shibboleth' },
  { id: 'unicamp', name: 'University of Campinas', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufrj', name: 'Federal University of Rio de Janeiro', country: 'BR', authMethod: 'shibboleth' },
  { id: 'unesp', name: 'São Paulo State University', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufmg', name: 'Federal University of Minas Gerais', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufrgs', name: 'Federal University of Rio Grande do Sul', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufsc', name: 'Federal University of Santa Catarina', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufpr', name: 'Federal University of Paraná', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufpe', name: 'Federal University of Pernambuco', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufc', name: 'Federal University of Ceará', country: 'BR', authMethod: 'shibboleth' },
  { id: 'ufba', name: 'Federal University of Bahia', country: 'BR', authMethod: 'shibboleth' },
  { id: 'unb', name: 'University of Brasília', country: 'BR', authMethod: 'shibboleth' },
  { id: 'uff', name: 'Federal Fluminense University', country: 'BR', authMethod: 'shibboleth' },
  { id: 'puc_rio', name: 'Pontifical Catholic University of Rio de Janeiro', country: 'BR', authMethod: 'shibboleth' },
  { id: 'fgv', name: 'Getulio Vargas Foundation', country: 'BR', authMethod: 'shibboleth' },

  // Other Latin America (15 universities)
  { id: 'buenos_aires', name: 'University of Buenos Aires', country: 'AR', authMethod: 'shibboleth' },
  { id: 'chile', name: 'University of Chile', country: 'CL', authMethod: 'shibboleth' },
  { id: 'catolica_chile', name: 'Pontifical Catholic University of Chile', country: 'CL', authMethod: 'shibboleth' },
  { id: 'unam', name: 'National Autonomous University of Mexico', country: 'MX', authMethod: 'shibboleth' },
  { id: 'tecnologico_monterrey', name: 'Tec de Monterrey', country: 'MX', authMethod: 'shibboleth' },
  { id: 'andina', name: 'University of the Andes (Colombia)', country: 'CO', authMethod: 'shibboleth' },
  { id: 'nacional_colombia', name: 'National University of Colombia', country: 'CO', authMethod: 'shibboleth' },
  { id: 'costa_rica', name: 'University of Costa Rica', country: 'CR', authMethod: 'shibboleth' },
  { id: 'nacional_cordoba', name: 'National University of Córdoba', country: 'AR', authMethod: 'shibboleth' },
  { id: 'concepcion', name: 'University of Concepción', country: 'CL', authMethod: 'shibboleth' },
  { id: 'simon_bolivar', name: 'Simón Bolívar University', country: 'VE', authMethod: 'shibboleth' },
  { id: 'cayetano', name: 'Universidad Peruana Cayetano Heredia', country: 'PE', authMethod: 'shibboleth' },
  { id: 'san_marcos', name: 'National University of San Marcos', country: 'PE', authMethod: 'shibboleth' },
  { id: 'ecuador', name: 'Central University of Ecuador', country: 'EC', authMethod: 'shibboleth' },
  { id: 'panama', name: 'University of Panama', country: 'PA', authMethod: 'shibboleth' },
];

// Total: 358 universities across 6 continents
console.log(`Total universities: ${UNIVERSITIES.length}`);
